### ISSUE TITLE
unoconv renderer temp folder should be created if it doesn't exist

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.civioffice#10]
Since the `unoconv` renderer's temp folder is suggested to be within CiviCRM's `templates_c` directory, CiviOffice should re-create this directory if it doesn't exist, as the `templates_c` directory is supposed to be safe to be emptied. Currently, the renderer's validation fails if the configured temp directory does not exist.

**Comment by jensschuppe** [comment]
@dontub is this still an issue after #40?

**Comment by dontub** [comment]
No, that's not an issue anymore.
