### ISSUE TITLE
Is development status still dev, or stable?

### ISSUE THREAD

**Issue by JoeMurray** [systopia/de.systopia.civioffice#22]
Is this production ready? It seems like it is likely already in production, and you have great documentation. Just checking because info.xml says it is still dev version 0.10.

**Comment by peth-systopia** [comment]
Hi Joe,

thanks for reaching out. We are currently finishing 0.10, next up is 1.0. The tool is already in productive use by some organisations, however we will consider it stable after the last fixes and improvements in version 1.0. Feel free to try it out though, it can already do lots of good stuff.

Best
Martin

**Comment by JoeMurray** [comment]
Thanks!
