### ISSUE TITLE
Errors from static code analysis

### ISSUE THREAD

**Issue by abugey** [systopia/de.systopia.civioffice#26]
PHPStorm inspect code feature found the following errors:

-     .editorconfig: line 224: 'global' is not allowed here
-     LiveSnippet.php: undefined variable $option_group_id

**Comment by jensschuppe** [comment]
`.editorconfig` is being generated by PHPStorm, so that includes proprietary options we wanted to keep for helping with code style (whether or not that's good practice in the first place).
