### ISSUE TITLE
angle brackets get resolved to &lt; and &gt;

### ISSUE THREAD

**Issue by jofranz** [systopia/de.systopia.civioffice#3]
## General
Unfortunately, we get `&lt;` and `&gt;` from civi backend if we use `<` or `>` symbols. This could lead to an ugly output in final tokenreplaced documents, if these symbols are used.

----

The UI mapps those back to angle brackets
![brackets_view](https://user-images.githubusercontent.com/12087462/113285702-8cac3d00-92eb-11eb-8dfa-0ed2f83dffe3.png)

----

Internally they are saved as `&lt;` and `&gt;`
![brackets_ui_edit](https://user-images.githubusercontent.com/12087462/113285701-8c13a680-92eb-11eb-90c0-c4c41bd3399c.png)

As the backend uses `&lt;` and `&gt;` this is also visible in the final document
![brackets_doc](https://user-images.githubusercontent.com/12087462/113285698-8b7b1000-92eb-11eb-9238-68b650eccb4c.png)

## Approach
We could decode them back to `<` and `>` with `htmlspecialchars_decode()`. This is currently postponed as it might lead to further problems

**Comment by jensschuppe** [comment]
I thought this was fixed somehow, but can't remember when and how ... please reopen when this still is an issue.
