### ISSUE TITLE
Token replacement via PhpWord with `setComplexValue()`

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.civioffice#30]
Instead of replacing the entire paragraph (or: PhpWord element) that contains a token with its content (when it contains HTML that converts to multiple OOXML elements), the element should be split around the token. This is what `\PhpOffice\PhpWord\TemplateProcessor::setComplexValue()` seems to be doing.

**Comment by dontub** [comment]
Fixed by #62.
