### ISSUE TITLE
Move pictures with text

### ISSUE THREAD

**Issue by Astriel07** [systopia/de.systopia.civioffice#35]
Dear Systopia Team,

Thank you very much for developing and sustaining CiviOffice. We're using CiviOffice in the organization and have also tested the extension "more greetings" in combination with it. The plan was to allow dynamic addresses that have a varying number of lines e.g.:

```
Name
Street
Postal Code / City
```

vs.

```
Name
Street
Addition
Postal Code / City
```

This alone works great. The issue is now: When I have pictures in the following text after the address they are in a fixed position on the page even if they are set as "move with text" in the word document. This means that in some output documents the pictures will be in the wrong place. If that isn't to complex it would be great if you could enable pictures to move with the text in the documents renderer.

Best Regards,
Philipp (with Das NETTZ)

**Comment by jofranz** [comment]
Civioffice is just replacing words in documents. I guess you should give the address box enough space in order to prevent images from moving as there is no easy or upcoming fix for this
