### ISSUE TITLE
Resolve 5.60+ false positive in CustomData code

### ISSUE THREAD

**Issue by jofranz** [systopia/de.systopia.civioffice#42]
Our `check-extensions-for-removed-core-code.sh` which is scanning for 5.60+ incompatibilities flags CiviOffice as incompatible, as [this search term](https://github.com/systopia/legacycode/#find-out-if-your-extension-might-have-a-compatibility-problem) finds following code:

```de.systopia.civioffice/CRM/Civioffice/CustomData.php:
$activity_type = CRM_Core_OptionGroup::getValue('activity_type', $activity_type, 'name');
```

In most of your extensions `syncCustomGroup()` isn't used. It would be great to either remove this method here or to update to a newer [Custom-Data-Helper](https://github.com/systopia/Custom-Data-Helper/tags) version.

**Comment by bjendres** [comment]
I'm not sure I understand what you mean? Is there maybe a copy&paste error?

**Comment by jofranz** [comment]
Yes. It would be sufficient to update/swap it.
