### ISSUE TITLE
UnoConv parallel execution

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.civioffice#6]
It seems like the ``unoconv`` tool used by the ``LocalUnoconv`` converter cannot (easily) handle parallel execution.

There should be a way, see e.g.
* https://github.com/unoconv/unoconv/issues/172
* https://github.com/unoconv/unoconv/issues/225
* https://github.com/unoconv/unoconv/issues/225#issuecomment-538912101

However, in the short run we'll disable parallel execution.

**Comment by jensschuppe** [comment]
Seems this has been fixed. Please reopen if not, @bjendres.

**Comment by bjendres** [comment]
> Reopening as `unoconv` doesn't support parallel execution out of the box

I would suggest to create another ticket for that.

**Comment by bjendres** [comment]
> Also, is this related to #5?

Yes, I believe this (also) fixes #5 - I might be wrong though.

**Comment by jofranz** [comment]
> > Also, is this related to #5?
> 
> Yes, I believe this (also) fixes #5 - I might be wrong though.

Indeed closes #5
